In [1]:
import numpy as np

## Задание 5

В векторе x надо заполнить каждый нулевой элемент предыдущим ненулевым значением.

In [9]:
x = np.array([8, 0, 0, 1, 0, 0, 0, -17.5, 0])
y = np.arange(len(x))
y[x == 0] = 0
y = np.maximum.accumulate(y)
print (x[y])

[  8.    8.    8.    1.    1.    1.    1.  -17.5 -17.5]


## Задание 6

Надо вычислить приближённое значение функции f(x) = ln(1 + x) в точке x0 с помощью разложения в ряд Тейлора N-го порядка в окрестности нуля.



In [17]:
x0=0.01
N=1000

a = np.arange(1, N+1)
def Taylor(x0, n):
    return ((-1)**(n+1))*(x0**n)/n
y = Taylor(x0, a).sum()
print('ln(1+%f) = %f' %(x0, y))

ln(1+0.010000) = 0.009950


## Задание 7

Дана матрица X «объекты-признаки» размера m x n: число строк m — это количество объектов, а число столбцов n — количество признаков. Каждая строка представляет собой описание объекта выборки в виде набора значений его признаков. Каждый же столбец содержит значения определённого признака на всех объектах выборки. Надо найти выборочное среднее и ковариационную матрицу выборки X, не пользуясь специальными numpy функциями mean и cov.

In [24]:
x = np.array([[175, 4], [20, 2], [25, 8]]) 

summ = x.sum(axis=0)
m=1
m, n = x.shape
mean = summ/m
print('выборочное среднее:\n', mean)
print ('выборочное среднее по спец. функции "mean":\n', np.mean(x, axis=0))

deviation = x - np.reshape(np.repeat(mean, m), (n,-1)).T
Q = np.dot(deviation.T, deviation)/(m-1)
print('ковариационная матрица выборки:\n', Q)
print ('ковариационная матрица выборки по спец. функции "cov":\n', np.cov(x.T))

выборочное среднее:
 [73.33333333  4.66666667]
выборочное среднее по спец. функции "mean":
 [73.33333333  4.66666667]
ковариационная матрица выборки:
 [[7758.33333333  -43.33333333]
 [ -43.33333333    9.33333333]]
ковариационная матрица выборки по спец. функции "cov":
 [[7758.33333333  -43.33333333]
 [ -43.33333333    9.33333333]]
